main: io.github.sindastra.BukkitWalkPaths.Main
version: 1.3.0
name: SindastrasWalkPaths
commands:
    walkpath:
        description: Walk a path!
        usage: Use "/walkpath help" for more details.
